[project]
name = "emaktab-reload"
version = "0.1.0"
description = "eMaktab bot reconstruct"
authors = [
    { name = "Cybernoob", email = "ibrasamandar.2009@gmail.com" }
]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.12,<3.14"
dependencies = [
    "aiogram",
    # "uvloop",  # windows not supported (uncomment if you are on Linux)
    "ujson",

    # Other packages
    "structlog",
    "pydantic",
    "fluent.runtime",
    "fluent.syntax",
    "colorama",

    "asyncpg",
    "sqlalchemy",
    "alembic",
    "bs4 (>=0.0.2,<0.0.3)",
    "lxml (>=6.0.2,<7.0.0)",
    "aiosqlite (>=0.21.0,<0.22.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
package-mode = false

[tool.poetry.group.gui.dependencies]
flet = "^0.28.3"

