"""Change emaktab_users, ondelete=cascad

Revision ID: 108f9a746fb3
Revises: 8cd53263ed10
Create Date: 2025-10-01 22:46:06.208538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '108f9a746fb3'
down_revision: Union[str, None] = '8cd53263ed10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('emaktab_users_telegram_id_fkey'), 'emaktab_users', type_='foreignkey')
    op.create_foreign_key(None, 'emaktab_users', 'telegram_users', ['telegram_id'], ['telegram_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'emaktab_users', type_='foreignkey')
    op.create_foreign_key(op.f('emaktab_users_telegram_id_fkey'), 'emaktab_users', 'telegram_users', ['telegram_id'], ['telegram_id'])
    # ### end Alembic commands ###
