"""added user settings

Revision ID: adea76644eb9
Revises: b28115e1e9db
Create Date: 2025-10-30 18:27:19.685551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adea76644eb9'
down_revision: Union[str, None] = 'b28115e1e9db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default='f', nullable=False),
    sa.Column('auto_up_activity', sa.Boolean(), server_default='f', nullable=False),
    sa.Column('auto_send_schedule', sa.Boolean(), server_default='f', nullable=False),
    sa.Column('auto_send_lessons', sa.Boolean(), server_default='f', nullable=False),
    sa.ForeignKeyConstraint(['telegram_id'], ['telegram_users.telegram_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_settings_id'), 'users_settings', ['id'], unique=False)
    op.add_column('emaktab_users', sa.Column('is_correct', sa.Boolean(), server_default='t', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emaktab_users', 'is_correct')
    op.drop_index(op.f('ix_users_settings_id'), table_name='users_settings')
    op.drop_table('users_settings')
    # ### end Alembic commands ###
